urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView, UpdateView
from django.contrib.auth.decorators import login_required


from voting.views import xmlhttprequest_vote_on_object

from hypotheses.views import detail, HypothesisCreate, HypothesisEdit
from hypotheses.models import Hypothesis
from evidences.models import Evidence
from evidences.views import evidencedetail, EvidenceCreate, EvidenceEdit
from UTIs.models import Description, Summary
from UTIs.views import SummaryCreate, DescriptionCreate, HypothesisSummaryList

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
     #home view
     (r'^$', ListView.as_view(model=Hypothesis,)),

     #accounts (login, logout etc)
     (r'^accounts/', include('registration.urls')),
     #(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
     #(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
     
     (r'^hypothesis/add', login_required(HypothesisCreate.as_view(model=Hypothesis))),
     (r'^hypothesis/(?P<hypothesis_id>\d+)/$',detail),
     (r'^hypothesis/(?P<hypothesis_id>\d+)/summaries/$', HypothesisSummaryList.as_view()),
     (r'^hypothesis/(?P<pk>\d+)/edit/$', HypothesisEdit.as_view(model=Hypothesis)),
     (r'^hypothesis/(?P<hypothesis_id>\d+)/add_evidence/$', login_required(EvidenceCreate.as_view(model=Evidence))),
     (r'^hypothesis/(?P<hypothesis_id>\d+)/add_description/$', login_required(DescriptionCreate.as_view(model=Description))),
     (r'^hypothesis/(?P<hypothesis_id>\d+)/add_summary/$', login_required(SummaryCreate.as_view(model=Summary))),
     (r'^evidence/(?P<object_id>\d+)/$',evidencedetail),
     (r'^evidence/(?P<pk>\d+)/edit/$',EvidenceEdit.as_view(model=Evidence)),
     (r'^evidence/(?P<object_id>\d+)/(?P<direction>up|down|clear)vote/?$',xmlhttprequest_vote_on_object, dict(model=Evidence)),
     (r'^evidence/(?P<evidence_id>\d+)/add_description/$', login_required(DescriptionCreate.as_view(model=Description))),
     
     (r'^summary/(?P<object_id>\d+)/(?P<direction>up|down|clear)vote/?$',xmlhttprequest_vote_on_object, dict(model=Summary)),  
            
     (r'^admin/', include(admin.site.urls)),
)

hypotheses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from evidences.models import Evidence
from UTIs.models import Description, Summary
from voting.models import Vote
from django.conf import settings




class Hypothesis(models.Model):
	proposer=models.ForeignKey(User,related_name='hypothesis_proposerset',editable=False)
	proposer_description=models.CharField(max_length=200, help_text="describe the hypothesis in 200 characters or less", verbose_name="Hypothesis")
	originator_name=models.CharField(max_length=100, help_text="Name of person who originally proposed hypothesis. If it is your hypothesis, type \'me\'")
	originator_unique=models.CharField(max_length=100, blank=True, editable=False)
	originator_user=models.ForeignKey(User, blank=True, null=True, related_name='hypothesis_originatorset', editable=False)
	status=models.CharField(max_length=50, blank=True, null=True, editable=False)
		
	#map back generic relations to Summaries and Descriptions
	summaries = generic.GenericRelation(Summary, content_type_field='summ_type',object_id_field='object_id')
	descriptions = generic.GenericRelation(Description, content_type_field='desc_type',object_id_field='object_id')
	
	def __unicode__(self):
		return self.proposer_description
	
	def get_absolute_url(self):
		return "%shypothesis/%s/" % (settings.URLBASE, self.id)

	def get_disqus_id(self):
		return "hypothesis_%s" % self.id

	def get_evidences_voteinfo(self):
		scores=Vote.objects.get_scores_in_bulk(self.evidenceset.all())
		return scores

	def get_top_evidence_ids(self):
		#use e.g. Evidence.objects.in_bulk(<hypothesis>.get_top_evidences)
		scores=self.get_evidences_voteinfo()
		sorted_ids=sorted(scores, key=lambda x: (scores[x]['score'],scores[x]['num_up_votes']),reverse=True)
		return sorted_ids

	def get_ordered_evidence_items(self):
		voted_ids=self.get_top_evidence_ids()
		other_ids=[item.id for item in self.evidenceset.exclude(id__in=voted_ids)]
		all_ids=voted_ids+other_ids
		#in_bulk doesn't preserve order to need to reorder afterwards
		unordered = Evidence.objects.in_bulk(all_ids)	
		reordered = [unordered.get(id,None) for id in all_ids]
		return filter(None, reordered)

	def get_summaries_voteinfo(self):
		scores=Vote.objects.get_scores_in_bulk(self.summaries.all())
		return scores

	def get_top_summary_ids(self):
		scores=self.get_summaries_voteinfo()
		sorted_ids=sorted(scores, key=lambda x: (scores[x]['score'],scores[x]['num_up_votes']),reverse=True)
		return sorted_ids

	def get_ordered_summary_items(self):
		voted_ids=self.get_top_summary_ids()
		other_ids=[item.id for item in self.summaries.exclude(id__in=voted_ids)]
		all_ids=voted_ids+other_ids
		unordered = Summary.objects.in_bulk(all_ids)	
		reordered = [unordered.get(id,None) for id in all_ids]
		return filter(None, reordered)	
		
	def get_descriptions_voteinfo(self):
		scores=Vote.objects.get_scores_in_bulk(self.descriptions.all())
		return scores
		
	def get_top_description_ids(self):
		scores=self.get_descriptions_voteinfo()
		sorted_ids=sorted(scores, key=lambda x: (scores[x]['score'],scores[x]['num_up_votes']),reverse=True)
		return sorted_ids	
	
	def get_ordered_description_items(self):
		voted_ids=self.get_top_description_ids()
		other_ids=[item.id for item in self.descriptions.exclude(id__in=voted_ids)]
		all_ids=voted_ids+other_ids
		unordered = Description.objects.in_bulk(all_ids)	
		reordered = [unordered.get(id,None) for id in all_ids]
		return filter(None, reordered)

templates/addthis_large.html
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_preferred_5"></a>
<a class="addthis_button_preferred_6"></a>
<a class="addthis_button_compact"></a>
<a class="addthis_counter addthis_bubble_style"></a>
</div>
<!-- AddThis Button END -->

templates/addthis_small.html
<!-- AddThis Button BEGIN -->
<a class="addthis_button grid_3" href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=ra-4fb69fc26ae9b252"><img src="http://s7.addthis.com/static/btn/v2/lg-bookmark-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4fb69fc26ae9b252"></script>
<!-- AddThis Button END -->


<!-- AddThis Button BEGIN 
<div class="addthis_toolbox addthis_default_style grid_3">
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>
<a class="addthis_button_compact"></a>
</div>
-->
<div class="clear"></div>

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">


<html lang="en">
	<head>
		<title>{% block title %}hypothify{% endblock %}</title>
		{% include 'stylesheets.html' %}
		{% block extra_stylesheets %}{% endblock %}
		{% block header_extra %}{% endblock %}
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="description" content="{% block description %}{% endblock %}">
		<meta name="keywords" content="{% block keywords %}{% endblock %}">

		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4fb8f977245af1d2"></script>
		<script type="text/javascript">var addthis_config = {ui_header_background:"#333",ui_cobrand:"hypothify",data_track_clickback:true};</script>
	</head>

	<body>
		
			<div id="topbar">
				<div class="container_16">
					<a class="grid_12 omega" href="http://www.hypothify.com"><b>hypothify</b></a>
					<p id="accounts_topline" class="grid_4 alpha right">
						{% if user.is_anonymous %}
							<a href="{{urlbase}}accounts/login/">login</a> | <a href="{{urlbase}}accounts/register/">sign up</a>
						{% else %}
							logged in as <a href="{{user.get_absolute_url}}" class="boldlink">{{user}}</a> | <a href="{{urlbase}}accounts/logout/">logout</a>
						{% endif %}
					</p>
				</div>
			</div>
			<div class="container_16" id="pagebody">
			<div class="clear"></div>
			
			{% block pagecontent %}
			{% endblock %}
		

			
			
			{% block footer %}
				<div class="grid_4">&nbsp</div>
				<h4 class="grid_10">Hypothify footer goes here</h4>
			{% endblock %}			
		</div>
	</body>

</html>

templates/base_evidence.html
{% extends "base.html" %}

{% block title%}{{block.super}}: {% endblock %}

{% block pagecontent %}
	
	{% block hypothesis %}
	{% endblock %}
	
	<div class="grid_11" id="leftcolumn">
		{% block evidence%}
		{% endblock %}

		{% block share%}
		{% endblock%}
		
		{% block comments %}
		{% endblock %}

	</div>
	
	<div class="grid_5" id="rightcolumn">
		{% block rightcolumn%}

		{% endblock%}	
	</div>

	
	
{% endblock %}

templates/base_form.html
{% extends "base.html" %}

{% block title%}{{block.super}}: {% endblock %}

{% block pagecontent %}
	
	<h2 class="grid_16">
	{% block form_info %}
	{% endblock %}
	</h2>
	<div class="clear"></div>
	
	<div id="form_error" class="grid_12 prefix_2">
		{% block form_error %}
		{% endblock %}
	</div>
	
	<div id="form" class="grid_12 prefix_2">
		{% block form %}
		{% endblock %}
	</div>
	<div class="clear"></div>
	
	
	
{% endblock %}

templates/base_home.html
{% extends "base.html" %}
{% block title%}{{block.super}}: home{% endblock %}

{% block pagecontent %}
	<h1 class="grid_11 prefix_1">hypotheses</h1>
	<div id="actionbox" class="grid_4 omega">
		<p id="actiontext"><a href="{{urlbase}}hypothesis/add/">Add a hypothesis </a></p>
	</div>
	<div class="clear"></div>
	{% block hypothesis_list%}
	{% endblock %}
	<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    		var disqus_developer = 1; // developer mode is on
    		var disqus_shortname = 'hypothify-test'; // required: replace example with your forum shortname
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
	</script>
{% endblock%}

templates/base_hypotheses.html
{% extends "base.html" %}

{% block title%}{{block.super}}: {% endblock %}

{% block pagecontent %}
	{% block hypothesis %}
	{% endblock %}

	{% block summary %}
	{% endblock %}
	
	{% block evidence%}
	{% endblock %}	
{% endblock %}

templates/base_hypothesis.html
{% extends "base.html" %}

{% block title%}{{block.super}}: {% endblock %}

{% block pagecontent %}
	
	{% block hypothesis %}
	{% endblock %}
	
	<div class="grid_11" id="leftcolumn">
		{% block summary %}
		{% endblock %}
	
		{% block evidence%}
		{% endblock %}

		{% block share%}
		{% endblock%}
		
		{% block comments %}
		{% endblock %}

	</div>
	
	<div class="grid_5" id="rightcolumn">
		{% block rightcolumn%}

		{% endblock%}	
	</div>

{% endblock %}

templates/disquscommentcounter.html
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'hypothify-test'; // required: replace example with your forum shortname
	var disqus_developer = 1; // developer mode is on
	
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

templates/stylesheets.html
	<link rel="stylesheet" type="text/css" media="all" href="{{urlbase}}static/reset.css" />
	<link rel="stylesheet" type="text/css" media="all" href="{{urlbase}}static/960_16_col.css" />
	<link rel="stylesheet" type="text/css" media="all" href="{{urlbase}}static/hypothify_styles.css" />